function(add_hecate_dialect dialect dialect_namespace)
  set(LLVM_TARGET_DEFINITIONS ${dialect}.td)
  mlir_tablegen(${dialect}.h.inc -gen-op-decls)
  mlir_tablegen(${dialect}.cpp.inc -gen-op-defs)
  mlir_tablegen(${dialect}Types.h.inc -gen-typedef-decls -typedefs-dialect=${dialect_namespace})
  mlir_tablegen(${dialect}Types.cpp.inc -gen-typedef-defs -typedefs-dialect=${dialect_namespace})
  mlir_tablegen(${dialect}Dialect.h.inc -gen-dialect-decls -dialect=${dialect_namespace})
  mlir_tablegen(${dialect}Dialect.cpp.inc -gen-dialect-defs -dialect=${dialect_namespace})
  add_public_tablegen_target(Hecate${dialect}IncGen)
  add_dependencies(mlir-headers Hecate${dialect}IncGen)
endfunction()

function(add_hecate_pattern pattern dialect_namespace)
  set(LLVM_TARGET_DEFINITIONS ${pattern}.td)
  mlir_tablegen(${pattern}Pattern.inc -gen-rewriters -dialect=${dialect_namespace})
  add_public_tablegen_target(Hecate${pattern}IncGen)
  add_dependencies(mlir-headers Hecate${pattern}IncGen)
endfunction()

# Declare a dialect in the include directory
function(add_hecate_interface interface)
  set(LLVM_TARGET_DEFINITIONS ${interface}.td)
  mlir_tablegen(${interface}.h.inc -gen-op-interface-decls)
  mlir_tablegen(${interface}.cpp.inc -gen-op-interface-defs)
  mlir_tablegen(${interface}Types.h.inc -gen-type-interface-decls)
  mlir_tablegen(${interface}Types.cpp.inc -gen-type-interface-defs)
  add_public_tablegen_target(Hecate${interface}IncGen)
  add_dependencies(mlir-generic-headers Hecate${interface}IncGen)
endfunction()
